# Done to increase the memory available to gradle.
kotlin.code.style=official
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

minecraft_version=26.2
loader_version=0.19.2
fabric_version=0.152.1+26.2

# Mod Properties
mod_version=1.0.0
mod_group=com.pokeskies.fabricpluginmessaging
mod_id=fabricpluginmessaging
mod_name=FabricPluginMessaging
